# Generated by Django 3.2 on 2021-06-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='good_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
    ]
