# Generated by Django 3.2 on 2021-06-01 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_points', models.IntegerField(default=0)),
                ('belong', models.CharField(choices=[('総合人間学部', '総合人間学部'), ('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('理学部', '理学部'), ('医学部医学科', '医学部医学科'), ('医学部人間健康学科', '医学部人間健康学科'), ('薬学部', '薬学部'), ('工学部地球工学科', '工学部地球工学科'), ('工学部建築学科', '工学部建築学科'), ('工学部物理工学科', '工学部物理工学科'), ('工学部電気電子工学科', '工学部電気電子工学科'), ('工学部情報学科', '工学部情報学科'), ('工学部工業化学科', '工学部工業化学科'), ('農学部資源生物科学科', '農学部資源生物科学科'), ('農学部応用生命科学科', '農学部応用生命科学科'), ('農学部地域環境工学科', '農学部地域環境工学科'), ('農学部食料・環境経済学科', '農学部食料・環境経済学科'), ('農学部森林科学科', '農学部森林科学科'), ('農学部食品生物科学科', '農学部食品生物科学科')], max_length=50)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hide', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='best',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='condition',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='tag',
            field=models.CharField(blank=True, choices=[('総合人間学部', '総合人間学部'), ('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('理学部', '理学部'), ('医学部医学科', '医学部医学科'), ('医学部人間健康学科', '医学部人間健康学科'), ('薬学部', '薬学部'), ('工学部地球工学科', '工学部地球工学科'), ('工学部建築学科', '工学部建築学科'), ('工学部物理工学科', '工学部物理工学科'), ('工学部電気電子工学科', '工学部電気電子工学科'), ('工学部情報学科', '工学部情報学科'), ('工学部工業化学科', '工学部工業化学科'), ('農学部資源生物科学科', '農学部資源生物科学科'), ('農学部応用生命科学科', '農学部応用生命科学科'), ('農学部地域環境工学科', '農学部地域環境工学科'), ('農学部食料・環境経済学科', '農学部食料・環境経済学科'), ('農学部森林科学科', '農学部森林科学科'), ('農学部食品生物科学科', '農学部食品生物科学科'), ('学校生活', '学校生活'), ('全学共通科目', '全学共通科目')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
        migrations.AddField(
            model_name='goodmodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_good', to='Qapp.answermodel'),
        ),
        migrations.AddField(
            model_name='goodmodel',
            name='gooder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_good', to=settings.AUTH_USER_MODEL),
        ),
    ]
