# Generated by Django 3.2 on 2021-06-06 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0002_auto_20210601_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='condition',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='date_settled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='condition',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
