# Generated by Django 3.2 on 2021-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0003_auto_20210606_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='解答内容'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='good',
            field=models.IntegerField(default=0, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像1'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像2'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像3'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='content',
            field=models.CharField(max_length=200, verbose_name='メッセージ内容'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='belong',
            field=models.CharField(choices=[('総合人間学部', '総合人間学部'), ('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('理学部', '理学部'), ('医学部医学科', '医学部医学科'), ('医学部人間健康学科', '医学部人間健康学科'), ('薬学部', '薬学部'), ('工学部地球工学科', '工学部地球工学科'), ('工学部建築学科', '工学部建築学科'), ('工学部物理工学科', '工学部物理工学科'), ('工学部電気電子工学科', '工学部電気電子工学科'), ('工学部情報学科', '工学部情報学科'), ('工学部工業化学科', '工学部工業化学科'), ('農学部資源生物科学科', '農学部資源生物科学科'), ('農学部応用生命科学科', '農学部応用生命科学科'), ('農学部地域環境工学科', '農学部地域環境工学科'), ('農学部食料・環境経済学科', '農学部食料・環境経済学科'), ('農学部森林科学科', '農学部森林科学科'), ('農学部食品生物科学科', '農学部食品生物科学科')], max_length=50, verbose_name='所属学部・学科'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ユーザー画像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='質問内容'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像1'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像2'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像3'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='tag',
            field=models.CharField(blank=True, choices=[('総合人間学部', '総合人間学部'), ('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('理学部', '理学部'), ('医学部医学科', '医学部医学科'), ('医学部人間健康学科', '医学部人間健康学科'), ('薬学部', '薬学部'), ('工学部地球工学科', '工学部地球工学科'), ('工学部建築学科', '工学部建築学科'), ('工学部物理工学科', '工学部物理工学科'), ('工学部電気電子工学科', '工学部電気電子工学科'), ('工学部情報学科', '工学部情報学科'), ('工学部工業化学科', '工学部工業化学科'), ('農学部資源生物科学科', '農学部資源生物科学科'), ('農学部応用生命科学科', '農学部応用生命科学科'), ('農学部地域環境工学科', '農学部地域環境工学科'), ('農学部食料・環境経済学科', '農学部食料・環境経済学科'), ('農学部森林科学科', '農学部森林科学科'), ('農学部食品生物科学科', '農学部食品生物科学科'), ('学校生活', '学校生活'), ('全学共通科目', '全学共通科目')], max_length=50, null=True, verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='質問タイトル'),
        ),
    ]
